<?php

/**
 * @file
 *  Adds the Google Analytics Pro2 plugin to JW player.
 *  More info at http://www.longtailvideo.com/addons/plugins/107/Google-Analytics-Pro
 *
 * @see http://drupal.org/node/1338964 - implementing plugins
 */

/**
 * Implements hook_jw_player_plugin_info().
 *
 * Register a jw_player preset plugin.
 */
function jw_player_gapro2_jw_player_plugin_info() {
  // Google Analytics Pro2 - http://www.longtailvideo.com/addons/plugins/107/Google-Analytics-Pro
  $plugins['gapro-2'] = array(
    'name' => t('Google Analytics Pro 2'),
    'description' => t('Google Analytics Pro 2 plugin for HTML5 JW player'),
    // Note: Each option should be in a valid FAPI format, as it is directly referenced in the preset settings form
    // #title could be omitted for the name of the option to be taken as default
    'config options' => array(
      'accountid' => array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#size' => 15,
        '#default_value' => variable_get('googleanalytics_account', '')
      ),
      'trackingobject' => array(
        '#type' => 'textfield',
        '#size' => 15,
        '#default_value' => '_gaq',
        '#description' => t('The Google Analytics tracking object, configured by default for asynchronous '.
                            'tracking mode. This will accept either Google Analytics tracking object '.
                            '(i.e. pageTracker) or a string representing the variable name (i.e. "_gaq"). '.
                            'Note that if you provide a string, it must be a globally accessible variable.')
      ),
      'trackstarts' => array(
        '#type' => 'select',
        '#options' => array('TRUE' => 'TRUE', 'FALSE' => 'FALSE'),
        '#default_value' => 'TRUE',
        '#description' => t('Controls whether data about video starts are sent to Google Analytics. '.
                            'One start event is sent each time a viewer begins playback from the first '.
                            'frame of the video. Note - This include starts that occur after the viewer '.
                            'pressed stop, or completed the video and pressed play again.')
      ),
      'trackpercentage' => array(
        '#type' => 'select',
        '#options' => array('TRUE' => 'TRUE', 'FALSE' => 'FALSE'),
        '#default_value' => 'TRUE',
        '#description' => t('Controls whether data about the percentage of the total video '.
                            'content played by the viewer is sent to Google Analytics.')
      ),
      'tracktime' => array(
        '#type' => 'select',
        '#options' => array('TRUE' => 'TRUE', 'FALSE' => 'FALSE'),
        '#default_value' => 'TRUE',
        '#description' => t('Controls whether data about the total time the viewer '.
                            'spent watching the video is sent to Google Analytics.')
      ),
      // @todo 'idstring' & 'hidden' variables need to be implemented for playlists
    ),
  );

  return $plugins;
}